sudo: required
language: node_js
node_js:
  - "8"
servicies: 
  - docker

before_install:
  - docker build -t sudheerasl/docker-react -f Dockerfile.dev .


script:
  - docker run sudheerasl/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-783122300362"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


