sudo: required
language: node_js
node_js:
  - "8"
servicies: 
  - docker

before_install:
  - docker build -t sudheerasl/docker-react -f Dockerfile.dev .


script:
  - docker run sudheerasl/docker-react npm run test -- --coverage
